[package]
name = "centerline"
version = "0.4.1"
authors = ["eadf"]
edition = "2018"
description = "Simple library for finding centerlines of 2D closed geometry"
readme = "README.md"
repository = "https://github.com/eadf/centerline.rs"
license = "AGPL-3.0"
keywords = ["centerline", "geometry"]
exclude = [
    "img/*",
    "idea/*",
    ".github/*",
]

[features]
console_debug = []
impl-wavefront = ["obj-rs"]
default = []

[dependencies]
num = "0.4"
ahash = "0.7"
vec_map = "0.8"
num-traits = "0.2"
yabf = {version="0.1",default-features=false}
boostvoronoi = "^0.8.4"
linestring = {version="0.4",default-features=false,features=["impl-cgmath", "impl-rayon"]}
cgmath = "0.18"
approx = "0.4"
thiserror = "1.0"
rayon = "1.5"
bitflags = "1.2"
ordered-float = "2.5"
obj-rs = { version = "0.6", optional = true }

[[example]]
name = "fltk_gui"
path = "example/centerline_gui.rs"
required-features = ["impl-wavefront"]

[[example]]
name = "cli"
path = "example/cli.rs"

[dev-dependencies]
fltk = "1.0"
itertools = "0.10"
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
