[package]
name = "centerline"
version = "0.0.3"
authors = ["eadf"]
edition = "2018"
description = "Work in progress"
readme = "README.md"
repository = "https://github.com/eadf/centerline.rs"
license = "AGPL-3.0"
keywords = ["geometry"]

[dependencies]
num = "^0.4.0"
fnv = "^1.0.7"
vec_map = "^0.8.2"
num-traits = "^0.2.14"
yabf = {version="^0.0.3",default-features=false}
#yabf = {path = "../yabf.rs"}
boostvoronoi = "^0.8.0"
#boostvoronoi = {path = "../boostvoronoi.rs"}
#boostvoronoi = { git = "https://github.com/eadf/boostvoronoi.rs" }
#linestring = {version="^0.0.14",default-features=false,features=["impl-cgmath"]}
#linestring = {path = "../linestring.rs",default-features=false,features=["impl-cgmath", "impl-rayon"]}
linestring = { git = "https://github.com/eadf/linestring.rs",default-features=false,features=["impl-cgmath","impl-rayon"]}
cgmath = "^0.18.0"
approx = "^0.4.0"
obj-rs = "^0.6.2"
thiserror = "^1.0.24"
rayon = "^1.5.0"
bitflags = "^1.2.1"

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"

[[example]]
name = "cli"
path = "example/cli.rs"

[dev-dependencies]
fltk = "^0.16.1"
itertools = "^0.10.0"
ordered-float = "^2.1.1"
criterion = "^0.3.4"

[features]
console_debug = []

[[bench]]
name = "bench"
harness = false
