[package]
name = "centerline"
version = "0.7.0"
authors = ["eadf"]
edition = "2021"
description = "Simple library for finding centerlines of 2D closed geometry"
readme = "README.md"
repository = "https://github.com/eadf/centerline.rs"
license = "AGPL-3.0"
keywords = ["centerline", "geometry", "median-axis"]
exclude = [
    "img/*",
    "idea/*",
    ".github/*",
]

[features]
console_debug = []
default = []

[dependencies]
ahash = "~0.7"
num-traits = "~0.2"
vob = "~3.0"
boostvoronoi = { version = "~0.10", features = ["cgmath"] }
linestring = "~0.8"
cgmath = "~0.18"
approx = "~0.5"
thiserror = "~1.0"
rayon = "~1.5"
bitflags = "~1.3"
ordered-float = "~2.8"
obj-rs = { version = "~0.7", optional = true }

[[example]]
name = "fltk_gui"
path = "example/centerline_gui.rs"
required-features = ["obj-rs"]

[[example]]
name = "cli"
path = "example/cli.rs"

[dev-dependencies]
fltk = "~1.2"
itertools = "~0.10"
criterion = "~0.3"

[build-dependencies]
version_check = "~0.9"

[[bench]]
name = "bench"
harness = false
