[package]
name = "centerline"
version = "0.1.0"
authors = ["eadf"]
edition = "2018"
description = "Simple library for finding centerlines of 2D closed geometry"
readme = "README.md"
repository = "https://github.com/eadf/centerline.rs"
license = "AGPL-3.0"
keywords = ["centerline", "geometry", "data-structures", "mathematics"]

[dependencies]
num = "^0.4.0"
fnv = "^1.0.7"
vec_map = "^0.8.2"
num-traits = "^0.2.14"
yabf = {version="^0.1.0",default-features=false}
#yabf = {path = "../yabf.rs",default-features=false}
#yabf = { git = "https://github.com/eadf/yabf.rs",default-features=false}
boostvoronoi = "^0.8.1"
#boostvoronoi = {path = "../boostvoronoi.rs"}
#boostvoronoi = { git = "https://github.com/eadf/boostvoronoi.rs" }
linestring = {version="^0.2.0",default-features=false,features=["impl-cgmath", "impl-rayon"]}
#linestring = {path = "../linestring.rs",default-features=false,features=["impl-cgmath", "impl-rayon"]}
#linestring = { git = "https://github.com/eadf/linestring.rs",default-features=false,features=["impl-cgmath","impl-rayon"]}
cgmath = "^0.18.0"
approx = "^0.4.0"
obj-rs = "^0.6.2"
thiserror = "^1.0.24"
rayon = "^1.5.0"
bitflags = "^1.2.1"
ordered-float = "^2.1.1"

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"

[[example]]
name = "cli"
path = "example/cli.rs"

[dev-dependencies]
fltk = "^1.0.0"
itertools = "^0.10.0"
criterion = "^0.3.4"

[features]
console_debug = []

[[bench]]
name = "bench"
harness = false
