[package]
name = "centerline"
version = "0.0.2"
authors = ["eadf"]
edition = "2018"
description = "Work in progress"
readme = "README.md"
repository = "https://github.com/eadf/centerline.rs"
license = "AGPL-3.0"
keywords = ["geometry"]

[dependencies]
num = "^0.3.1"
ordered-float = "^2.1.1"
fnv = "^1.0.7"
rb_tree = "^0.3.3"
vec_map = "^0.8.2"
num-bigint = "^0.3.1"
num-traits = "^0.2.14"
boostvoronoi = "^0.4.1"
#boostvoronoi = {path = "../boostvoronoi.rs"}
linestring = {version="^0.0.9", features = ["impl-cgmath"]}
#linestring = {path = "../linestring.rs", features = ["impl-cgmath"]}
cgmath = "^0.18.0"
approx = "^0.4.0"
obj-rs = "^0.6.2"
thiserror = "^1.0.24"
rayon = "^1.5.0"

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"

[dev-dependencies]
fltk = "^0.15.5"
itertools = "^0.10.0"
